---
prefer_indep_over_os_packages: false
osdeps_mode: all
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
typelib_cxx_loader: castxml
syskit_use_bundles: true
apt_dpkg_update: true
USE_PYTHON: true
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb

